### PR TITLE
parse: use same algorithm that reflect.Lookup to detect wire tags #179

### LINKED ISSUE #179: parse: use more robust algorithm to detect wire tags
We currently does a `strings.Contains` call to match the wire tags, which does not follow same algorithm that the reflect package uses.

### PR DESCRIPTION
**Pull request by u5surf**
Fixes #179 
This fix replaces tag detection using the same algorithm of `reflect.Lookup` into `strings.Contains` .

### CODE REVIEW

**Comment by jotdl** [comment]
Hi, 
I was just about tackling this issue, too. But then I saw you already submitted a pull request which is awesome!

I just wonder, couldn't the same behaviour be achieved by changing the `isPrevented` method to the approach below?

```go
import "reflect"
...

// isPrevented checks whether field i is prevented by tag "-".
// Since this is the only tag used by wire, we can do string comparison
// without using reflect.
func isPrevented(tag string) bool {
	return reflect.StructTag(tag).Get("wire") == "-"
}
```

I might be wrong, but the tests still succeed.
The only disadvantage I see is the import of the `reflect` package. But this shouldn't matter I think because _parse.go_ imports `fmt` which imports `reflect` anyways.
The benefit would be that all future improvements to `StructTag.Get` would be automatically applied here.

Why did you decide to copy the method from the `reflect.StructTag` type instead of reusing it?

**Comment by u5surf** [comment]
@jotdl Thank you for your reviewing. I just did the same approach you said but I thought whether this comment might have been special meaning.
https://github.com/google/wire/blob/ed1f30e1e8cc03225f15f4bb986f870c4c6dd394/internal/wire/parse.go#L865
Unless there are particular reason, I greate agree with your approach and I immediately fix using reflect.
What do you think @shantuo ?

**Comment by shantuo** [comment]
Hi @u5surf and @jotdl , thanks for the contribution!

I guess this one was my fault. I didn't know the shortcut of doing `reflect.StructTag` conversion while I wrote down the comment. I think doing what @jotdl suggest is fine.

**Comment by jotdl** [comment]
@shantuo: Thanks for your response! Great to hear that this looks fine.
@u5surf: Do you want to modify your pull request or should I submit a new one? What do you prefer?

**Comment by u5surf** [comment]
@shantuo Thanks your comments, I certainly understand that comment is unintentional.
@jotdl  I’ll modify that

**Pull request merged**
