### PR TITLE
internal/wire: use full go run command in go:generate comment

### LINKED ISSUE #160: Idea: use `go run` in generate line
[An idea](https://github.com/google/wire/issues/106#issuecomment-472934878) suggested by @steebchen is to use `//go:generate go run github.com/google/wire/cmd/wire` as the automatically inserted generate line for Wire output. This would have the advantage of always using a version of the code generator that's the same as the library being used, at the cost of perhaps some running time.

**EDIT** (Hit send too early) I don't think we want to make this change until Go Modules is the default, thus I'm marking this issue blocked.

### PR DESCRIPTION
**Pull request by steebchen**
Change the go:generate command to use the full go run ... command
to ensure the version specified in the current go module is used
instead of the global binary.

fix #160

### CODE REVIEW

**Comment by steebchen** [comment]
@googlebot I signed it!

**Comment by zombiezen** [comment]
Sorry for the delay. This is still on my radar to review, but I've been swamped with other life commitments. I will try to get to this sometime over the next few weeks.

**Comment by steebchen** [comment]
sure no worries

**Review by zombiezen — APPROVED** [review]
LGTM. Thanks for your patience!

**Pull request merged**
