### PR TITLE
Add goreportcard.com badge

### PR DESCRIPTION
**Pull request by dsxack**
It is one requirement of the pull request to add wire library to list https://github.com/avelino/awesome-go

https://github.com/avelino/awesome-go/pull/2965

https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md

https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md

### CODE REVIEW

**Comment by dsxack** [comment]
@googlebot I signed it!

**Comment by dsxack** [comment]
I close PR because PR to awesome-go is closed.

https://github.com/avelino/awesome-go/pull/2965

**Comment by zombiezen** [comment]
Hey @dsxack, thank you so much for trying to get Wire included on awesome-go. Really sorry to hear it didn't work out. I believe our test practices to be quite good for this project, but I'm not sure if there's anything we can do to demonstrate that in a way that awesome-go will accept. If you come up with something, I'd be happy to work with you on that.

**Comment by zombiezen** [comment]
Something worth pointing out: the files that contain the core Wire logic hover around 85%-94% coverage: https://codecov.io/gh/google/wire/tree/master/internal/wire

I think the average isn't weighted well: the main.go we intentionally don't test much because it's a thin wrapper around the well-tested library.

**Comment by dsxack** [comment]
@zombiezen thank you for response!

Would you mind if I try to increase the coverage of core Wire logic?

**Comment by zombiezen** [comment]
In general, yes, I'm supportive of PRs that increase test coverage as long as the tests don't introduce additional maintenance burden (e.g. brittle or hard-to-understand tests).

Definitely would love to see more coverage for parse.go. You should be able to do that by using the existing test infrastructure and exercising more cases.

copyast.go would likely need its own new unit test structure. Off the cuff, I would think the best way to do this would be something like:

```go
func TestCopyAST(t *testing.T) {
  tests := []struct{
    name string
    source string
  }{
    // ...
  }
  for _, test := range tests {
    // 1. Parse test.source using go/parser
    // 2. Call copyAST
    // 3. Use go-cmp to check that the returned AST is equivalent to the first
  }
}
```

**Pull request closed without merging**
